#!/bin/bash

# Welcome to your first Bash Script

hello_message="Hello, Team!"
current_dir=$(pwd)
readonly variable_wont_change="blue"

variable_wont_change="red"
echo "$hello_message from $current_dir your favorite color is $variable_wont_change"